[package]
name = "commit-helper"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "ch"
path = "src/main.rs"

[dependencies]
arboard = "3.4.1"
clap = { version = "4.4.12", features = ["derive"] }
inquire = { version = "0.6.2" }
